### PR TITLE
一下午时间初步完成了一个版本

### PR DESCRIPTION
**Pull request by unixzii**
Hi，在微博上看到这个小任务比较感兴趣，下午课余时间小试了一下。

现在完成了项目要求中列举的所有功能，部分功能实现方法略有不同。没有采用数据库存储文章列表，而是采用的 OkHttp Cache 的方式来缓存每次请求的响应。此外的一点小问题就是多图情况下 ViewPager 的性能还不是很高，有时间研究一下如何优化。

利益相关：iOS 开发者，Android 开发不熟练工。

### CODE REVIEW

**Comment by ryanhoo** [comment]
Good job. I will check this later. Also I suggest you add a label for this issue. You may pick either `for-fun` or `for-interview` from the right panel.

**Comment by ryanhoo** [comment]
@unixzii Hi, I checked out your project and compiled your app. Sure your code is not an A level, but it's quite good for an iOS developer, not to mention that you've finished it in only 5 hours. I doubt I can do it that fast. ;-)
Ah, it's user experience is one of the best. Well done!
You mentioned that you are still a student and GitHub profile shows that you live in Yantai, which is far away from Shenzhen. But we don't want to miss any potential developer, hereby on behalf of our company, I invite you to work with us. No specific position or title, depends on your interests.
Say yes I do.

**Comment by unixzii** [comment]
Thanks for your reviewing, up to this time I think I have to finished my education first. Certainly, I don't want to miss any opportunity to improve myself, I hope we can keep a connection perpetually, as soon as we need to take part in an internship, I expect that I could have a chance.

Best Regards.

**Comment by ryanhoo** [comment]
@unixzii Anytime

**Pull request closed without merging**
