### PR TITLE
项目完成 

### PR DESCRIPTION
**Pull request by YeungKC**

### CODE REVIEW

**Comment by ryanhoo** [comment]
Good job. I will check it later on . Also I suggest you add a label for this issue. You may pick either `for-fun` or `for-interview` from the right panel.

**Comment by YeungKC** [comment]
@ryanhoo 你好，我是为了面试的，另外，我貌似没有权限添加 label ？

**Comment by ryanhoo** [comment]
Label for-interview added.

**Comment by ryanhoo** [comment]
@YeungKC I had a glance at your project and application. It's pretty awesome, definitely a plus! 

But I wonder if you can complete the small test by strictly following the requirements mentioned in the documents. Based on your current work, it shouldn't take you too long. After all, I set the exercise to test something in you which is more than Java or Kotlin. You already showed me something that I care about, I would love to see the rest. 

Cheers.

**Comment by YeungKC** [comment]
@ryanhoo 我想你可能在说注释的问题，我刚才已经把我认为可能忽略的注释补全，请问你觉得还有什么问题呢？

**Comment by ryanhoo** [comment]
You misunderstood me. I wanna see how would you implement the specific features and specific design in a limited time. You already did a good job before this exercise but would you mind to do another simple version of gank.io with very specific requirements in a very limited time?

**Comment by YeungKC** [comment]
没错，平时我就一直在用 Gank.io 的 api 去实践我所设想东西，除去 github 的项目，我还写过非常多没有公开；我认为用此来评定对我而言不太公平，毕竟你所提出的需求除了 gif，Viewpager 列表中的轮播之后，其他并需求是很常见的，大部分人都做过。

如果可以，我希望先看你希望我在多长做一个多简单的 Gank.io？我再决定去不去做。

**Comment by ryanhoo** [comment]
You call this unfair? When did you started your project? How much time did you spend on that? How many times have you googled/stackoverflowed to solve your confusions? After all that you did a good job and I thought it should be flexible enough to adapt some new requirements. Honestly I was already impressed but I was just expecting to see a little more patience in you.

If you've ever asked me whether you can send me pull request with an existed project, we don't have to argue like this. 

You didn't ask me in the beginning. Then I wrote down my expectations, hoping you might say yes and impress me again, or, at least tell me why you won't do it. It's called communication.

You didn't ask me again. You thought that I cared so much about your missing comments then you plunged yourself in the amends. Then you came back with satisfaction and expected to get a YES from me.

I am sorry. I expected more than comments. 

I hope you can get it. // comprehension
If you didn't, you may talk to me. // communication
You're disappointed and run out of patience, then you became emotional. We can't afford to hire a co-worker like that. // collaboration

I wrote the proficiency exercise because it tests all the best characterics I care about, that's why I want you to finish it.

**Comment by YeungKC** [comment]
1，首先，我认为不公平原因是，我所参与到这个项目，首先应该评定项目；因为无论我事前或过程做了多少工作，但我的能力最终都是体现在项目里面。
2，做项目是有时间成本的，你并没有提到你所希望在多长时间做一个多简单的版本，我当然需要得知这些才决定是否去做，而不是贸然答应。
3，我想我们有误解的地方，我并没有失去耐心，我的一些个人信息可以体现出来，但我不愿在公开场合说明。

**Comment by ryanhoo** [comment]
1. How long should you spend in this project?

I remember someone asked me "if I can write this in Kotlin?", you are that guy aren't you? Then you should have read the weibo, it said "3 days top", you already built a great foundation then you should finish it in 1 or 2 days or even faster. Or you can say: `I hate repeating things, can I skip these stupid features? I already did that a 1000 times!` Sure! I will challenge you with something else.

2. How simple a simple version is?

I wrote everything in the README.md, I really hope you've read it thoroughly. It's as simple as the sketch design is.

**Comment by YeungKC** [comment]
1，通过在 WakaTime 显示，我到目前为止在此项目花费了 28 小时。
虽然列表功能已经做过很多，我相信大部分人都是一样，此项目我用了一些未曾用过得东西，比如开始我用 Realm 作为数据库，但是我最近不满意 get() 是在主线程运行不满意所以转用 GreenDao，然后发现并不能和 Kotlin 工作，所以最后采用了未曾在 Kotlin 用过的 AnkoSQLite。还有其他不再叙述，我想说明的是，虽然类似列表功能已经做过很多，但是也有方法令这个过程变得更有趣好玩。
2，我认为我基本完成这个简单的版本。
a Toolbar with tabs(Android, iOS, 前端), users can switch between these tabs to view posts under a specific topic// 完成
a List to display all kinds of posts//完成
pure text//完成
text with images(users can swipe to view images)//加上我在微博看到你所说需要轮播，完成
text with GIF(nice to be displayed as GIF, but you may consider it as a jpeg)//完成
pull down to refresh//完成
pull up(in the end of the List) to load history(older) posts//完成
only load the image as needed, make sure users don't have to download the images every time//完成
click on the item to view detailed information in a WebView//完成
cache all the posts in database so that you can display data when network is unavailable//具体执行策略我没有去和你沟通，可能存在理解不一样的地方，这点是我的问题

希望你能指出我所列出错误之处。

另外那个人是我。

**Comment by unixzii** [comment]
I think you must admit that you didn't solve your issues in a right way, for example, you said Realm cannot perform query on other threads, the way you "solve" it is to change your database framework, well, it doesn't matter cuz this is your own project, but if you are working within a team, a campany, can you keep cool and think up a better workaround, that shows you flexibility. I am an iOS developer and just a student, but just for fun, for challenging, I made it within 5 hours, of course I meet a lot of trouble, I even had not implemented ViewPager in a single RecyclerView, but by Googling it very quick, I did it. I think this is the point that interviewers want to figure out.

**Comment by YeungKC** [comment]
额，楼上这位我 @ 不到你，希望你能收到。
Realm 只能在主线程创建（其实只要线程持有 loop 就可以，相关操作可以在 Realm 文档查询）等操作，但是呢，他返回的 RealmResult 其实并不是真正获取到实体，而是 RealmObj 的代理类，当你真正去 get() 实体，才是获取数据。
但这种特性对于要读取数据完成后处理，那么肯定会有一个时间段是在 get() 数据，这段时间就很容易出现卡顿；如果我不去维护一个持有 Loop 的子线程，就不能做到将 IO 读取操作放到子线程，而维护一个持有 Loop 的子线程我认为成本过高，所以我思考了过后放弃了。
我开始使用 Realm 是因为我对 Realm 了解，可以更快的完成，但最后我选择了未曾在 Kotlin 使用过的其他数据库，我使用 Realm 已经有蛮长一段时间，很清楚了解他的好处与坏处。
之前没有过多说明，在此补充。

**Pull request closed without merging**
